// These values identify message recepients.
const ENVIRONMENT_DATA_TABLE = 0;
const DATA_MANAGER = 1;
const MODULE_MANAGER = 2;
const ENVIRONMENT = 3;
const MODULE_SELECTION_MENU = 4;
const INSPECTOR = 5;
const POPUP_MANAGER = 6;
const POPUP = 7;
const INPUT_MANAGER = 8;
const OUTPUT_MANAGER = 9;
const PIPELINE_MANAGER = 10;
const WORKER_MANAGER = 11;
const DOM_MANAGER = 12;
const MODULE = 13;
const INSPECTOR_CARD = 14;
const INSPECTOR_CARD_MAKER = 15;
const POPUP_CONTENT_MAKER = 16;

// Link Type Constants
/*const LOCAL_DATA_SOURCE = 0;
const REMOTE_DATA_IMAGE = 1;
const REMOTE_DATA_TABLE = 2;
const TABLE_OUTPUT = 3;
const TABLE_IMAGE = 4;
*/

// Link Type Constants
const LT_SOURCE = 0;
const LT_PROCESSOR = 1;
const LT_OUTPUT = 2;

const compositIcon = 'images/icons/flow-diagram-white.png'

/*export {
    ENVIRONMENT_DATA_TABLE, DATA_MANAGER, MODULE_MANAGER, ENVIRONMENT, MODULE_SELECTION_MENU, INPUT_MANAGER, INSPECTOR, INSPECTOR_CARD, INSPECTOR_CARD_MAKER, POPUP_MANAGER, POPUP, OUTPUT_MANAGER, PIPELINE_MANAGER, WORKER_MANAGER, DOM_MANAGER, compositIcon,
    LOCAL_DATA_SOURCE, REMOTE_DATA_IMAGE, REMOTE_DATA_TABLE, TABLE_IMAGE, TABLE_OUTPUT, MODULE, POPUP_CONTENT_MAKER
};*/
export {
    ENVIRONMENT_DATA_TABLE, DATA_MANAGER, MODULE_MANAGER, ENVIRONMENT, MODULE_SELECTION_MENU, MODULE,
    INPUT_MANAGER, INSPECTOR, INSPECTOR_CARD, INSPECTOR_CARD_MAKER, POPUP_MANAGER, POPUP, POPUP_CONTENT_MAKER, OUTPUT_MANAGER, PIPELINE_MANAGER, WORKER_MANAGER, DOM_MANAGER, compositIcon,
    LT_SOURCE, LT_PROCESSOR, LT_OUTPUT
};
